### PR TITLE
Stores autocomplete dropdown selection for products

### PR DESCRIPTION
**Pull request by kannans**
Why: 
 * User should able to search and select multiple stores.

This PR:
 * User can search and choose multiple stores from dropdown multi-selection.
 * Implemented Autocomplete for stores selection.
 * Updated `Spree::Admin::ProductsController`, specs and refactored few changes

### CODE REVIEW

**Comment by futhr** [comment]
Hi @kannans, most Ruby projects use 2 spaces, not 4 or with tabs. Otherwise it looks good.

**Comment by JDutil** [comment]
:+1: for 2 soft spaces. Also this broke a spec, but should be simple to fix I think it may just need to take the new autocomplete input into account. perhaps needs javascript driver or something enabled.

**Comment by kannans** [comment]
@futhr   Thanks for your feedback I will update necessary changes.
@JDutil Thanks for your feedback.

**Comment by priyank-gupta** [comment]
@kannans Are you still available for feedback changes ?

**Comment by kannans** [comment]
@JDutil  I have updated and fixed specs. Also refactored few codes. Kindly review it.  Let me know if anything need to be concerns.

**Comment by kannans** [comment]
@priyank-gupta Yes updated the feedback changes.

**Comment by priyank-gupta** [comment]
@kannans Thanks! :+1: 
@damianlegawiec ?

**Pull request merged**
