### PR TITLE
allow multiple taxons in product

### PR DESCRIPTION
**Pull request by arnie05**
Allow to affect multiple taxons in product when using spree-multi-domain : see #148

### CODE REVIEW

**Comment by vernondegoede** [comment]
This is great! Thank you for this @arnie05 . Had a hard time finding the issue and finally noticed the bad class_eval in Spree Multi Domain.

Good work 👍

**Comment by vernondegoede** [comment]
What's the reason this one's still open? This gem is currently not working properly. @damianlegawiec

**Comment by damianlegawiec** [comment]
@vernondegoede sorry we missed this one - we will rebase it against current master and merge it first thing on Monday

Thank you @arnie05 for this contribution 👍

**Comment by atarihomestar** [comment]
I'm having this same issue. Can you merge this in?

**Comment by damianlegawiec** [comment]
Merged via https://github.com/spree-contrib/spree-multi-domain/pull/166

**Pull request closed without merging**
