### PR TITLE
create 2-4-stable

### PR DESCRIPTION
**Pull request by arthurtalkgoal**

### CODE REVIEW

**Comment by futhr** [comment]
Hi @arthurtalkgoal, I wonder if you able to re-submit the `:zh` locale as `zh-CH` so it can be cherry-picked across branches.

**Comment by arthurtalkgoal** [comment]
Hi @futhr , I wish I can help.

So, I need to change the config/locales/zh.yml
to config/locales/zh-CH.yml and push accordingly?

**Comment by futhr** [comment]
Yes, and as a single commit pls.

**Comment by arthurtalkgoal** [comment]
Hi @futhr, I merged into one commit. Thanks

**Comment by JDutil** [comment]
@arthurtalkgoal could you please submit your translations within their own PR? We already have another 2-4-stable branch thanks for the effort though.

**Pull request closed without merging**
